In [ ]:
import numpy as np 
A = np.random.rand(2,2,2)
B = np.random.rand(3,3)
print(A)
print("\n nan", A.transpose())


[[[0.92611126 0.04090747 0.11309159]
  [0.74041531 0.98587852 0.80463345]
  [0.35641586 0.98942483 0.78799044]]

 [[0.43736196 0.29222046 0.87004542]
  [0.40111767 0.12740145 0.72994487]
  [0.01956166 0.1209467  0.875773  ]]

 [[0.56090359 0.76577992 0.12378198]
  [0.61636181 0.29662077 0.81457352]
  [0.01340732 0.77884992 0.12155138]]]

 nan [[[0.92611126 0.43736196 0.56090359]
  [0.74041531 0.40111767 0.61636181]
  [0.35641586 0.01956166 0.01340732]]

 [[0.04090747 0.29222046 0.76577992]
  [0.98587852 0.12740145 0.29662077]
  [0.98942483 0.1209467  0.77884992]]

 [[0.11309159 0.87004542 0.12378198]
  [0.80463345 0.72994487 0.81457352]
  [0.78799044 0.875773   0.12155138]]]


In [9]:
import numpy as np 
A = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
A=A+1
print(A)
print(A.flatten(order='F'))

[[[2 3]
  [4 5]]

 [[6 7]
  [8 9]]]
[2 6 4 8 3 7 5 9]


In [27]:
import numpy as np
A = np.random.rand(3,4,5)
A+=5
print(A)
print(A.ndim)

[[[5.65776987 5.21565666 5.19115105 5.7910393  5.30773604]
  [5.73373682 5.16023148 5.95532922 5.83603205 5.78826134]
  [5.20515671 5.60522394 5.04652504 5.81823003 5.48834288]
  [5.79731458 5.49953812 5.82150915 5.59413651 5.0087887 ]]

 [[5.87076247 5.93673561 5.73675701 5.68568926 5.00984337]
  [5.92553622 5.70977408 5.29973814 5.27182276 5.47871778]
  [5.04051546 5.12504466 5.54438405 5.36698221 5.13723398]
  [5.15180289 5.4696239  5.96914042 5.42925701 5.13776872]]

 [[5.74132974 5.41549736 5.6729768  5.12112892 5.63325911]
  [5.76669926 5.26510951 5.76958181 5.80283661 5.17575385]
  [5.83791257 5.15817486 5.11659587 5.82468374 5.511287  ]
  [5.14653679 5.30115817 5.11742276 5.90027373 5.80530418]]]
3
